apiVersion: v2
name: helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: confluent-local
    version: 0.1.0
    repository: file://./charts/confluent-local
    condition: confluent-local.enabled
  - name: cp-kafka
    version: 0.1.0
    repository: file://./charts/cp-kafka
    condition: cp-kafka.enabled
  - name: cp-schema-registry
    version: 0.1.0
    repository: file://./charts/cp-schema-registry
    condition: cp-schema-registry.enabled
  - name: cp-kafka-rest
    version: 0.1.0
    repository: file://./charts/cp-kafka-rest
    condition: cp-kafka-rest.enabled
  - name: cp-kafka-connect
    version: 0.1.0
    repository: file://./charts/cp-kafka-connect
    condition: cp-kafka-connect.enabled
  - name: cp-ksql-server
    version: 0.1.0
    repository: file://./charts/cp-ksql-server
    condition: cp-ksql-server.enabled
  - name: kafka-ui
    version: 0.1.0
    repository: file://./charts/kafka-ui
    condition: kafka-ui.enabled
