apiVersion: v1
kind: ConfigMap
metadata:
  name: local-confluent-kafka-cp-schema-registry-jmx-configmap
  labels:
    app: cp-schema-registry
    chart: cp-schema-registry-0.1.0
    release: local-confluent-kafka
    heritage: Helm
data:
  jmx-schema-registry-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
      - kafka.schema.registry:type=jetty-metrics
      - kafka.schema.registry:type=master-slave-role
      - kafka.schema.registry:type=jersey-metrics
    rules:
      - pattern : 'kafka.schema.registry<type=jetty-metrics>([^:]+):'
        name: "cp_kafka_schema_registry_jetty_metrics_$1"
      - pattern : 'kafka.schema.registry<type=master-slave-role>([^:]+):'
        name: "cp_kafka_schema_registry_master_slave_role"
      - pattern : 'kafka.schema.registry<type=jersey-metrics>([^:]+):'
        name: "cp_kafka_schema_registry_jersey_metrics_$1"