apiVersion: v1
kind: Service
metadata:
  name: local-confluent-kafka-cp-schema-registry
  labels:
    app: cp-schema-registry
    chart: cp-schema-registry-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  ports:
    - name: schema-registry
      port: 8081
  selector:
    app: cp-schema-registry
    release: local-confluent-kafka