apiVersion: v1
kind: ConfigMap
metadata:
  name: local-confluent-kafka-cp-kafka-rest-jmx-configmap
  labels:
    app: cp-kafka-rest
    chart: cp-kafka-rest-0.1.0
    release: local-confluent-kafka
    heritage: Helm
data:
  jmx-kafka-rest-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
      - kafka.rest:type=jetty-metrics
      - kafka.rest:type=jersey-metrics
    rules:
      - pattern : 'kafka.rest<type=jetty-metrics>([^:]+):'
        name: "cp_kafka_rest_jetty_metrics_$1"
      - pattern : 'kafka.rest<type=jersey-metrics>([^:]+):'
        name: "cp_kafka_rest_jersey_metrics_$1"