apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "confluent-local.fullname" . }}
  labels:
  {{- include "confluent-local.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}