apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-confluent-kafka-kafka-ui
  labels:
    app: kafka-ui
    chart: kafka-ui-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: kafka-ui
      release: local-confluent-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-ui
        release: local-confluent-kafka
    spec:
      containers:
        - name: kafka-ui
          image: docker.io/provectuslabs/kafka-ui:v0.7.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: PLAINTEXT://local-confluent-kafka-cp-kafka-headless:9092
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: first
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: http://local-confluent-kafka-cp-kafka-connect:8083
            - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
              value: http://local-confluent-kafka-cp-ksql-server:8088
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: http://local-confluent-kafka-cp-schema-registry:8081
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {}