apiVersion: v1
kind: Service
metadata:
  name: local-confluent-kafka-kafka-ui
  namespace: default
  labels:
    helm.sh/chart: kafka-ui-0.7.5
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: local-confluent-kafka
    app.kubernetes.io/version: "v0.7.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: local-confluent-kafka