apiVersion: v1
kind: Service
metadata:
  name: local-confluent-kafka-kafka-ui
  labels:
    app: kafka-ui
    chart: kafka-ui-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app: kafka-ui
    release: local-confluent-kafka