apiVersion: v1
kind: Service
metadata:
  name: local-confluent-kafka-cp-kafka
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  ports:
    - port: 9092
      name: broker
  selector:
    app: cp-kafka
    release: local-confluent-kafka