apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-confluent-kafka-cp-kafka
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: cp-kafka
      release: local-confluent-kafka
  serviceName: local-confluent-kafka-cp-kafka-headless
  podManagementPolicy: OrderedReady
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cp-kafka
        release: local-confluent-kafka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - cp-kafka
                    - key: "release"
                      operator: In
                      values:
                        - local-confluent-kafka
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: cp-kafka-broker
          image: "confluentinc/cp-enterprise-kafka:6.1.0"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9092
              name: kafka
          resources:
            {}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_HEAP_OPTS
              value: -Xms512M -Xmx512M
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "local-confluent-kafka-cp-zookeeper-headless:2181"
            - name: KAFKA_LOG_DIRS
              value: "/opt/kafka/data-0/logs"
            - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://local-confluent-kafka-cp-kafka-headless:9092"
            - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
              value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
              value: "3"
          # This is required because the Downward API does not yet support identification of
          # pod numbering in statefulsets. Thus, we are required to specify a command which
          # allows us to extract the pod ID for usage as the Kafka Broker ID.
          # See: https://github.com/kubernetes/kubernetes/issues/31218
          command:
            - sh
            - -exc
            - |
              export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_NAME}.local-confluent-kafka-cp-kafka-headless.${POD_NAMESPACE}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) && \
              exec /etc/confluent/docker/run
          volumeMounts:
            - name: datadir-0
              mountPath: /opt/kafka/data-0
  volumeClaimTemplates:
    - metadata:
        name: datadir-0
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "5Gi"