apiVersion: v1
kind: Service
metadata:
  name: local-confluent-kafka-cp-kafka-connect
  labels:
    app: cp-kafka-connect
    chart: cp-kafka-connect-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  ports:
    - name: kafka-connect
      port: 8083
  selector:
    app: cp-kafka-connect
    release: local-confluent-kafka