apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
  {{- include "kafka.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}