apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-confluent-kafka-cp-zookeeper
  labels:
    app: cp-zookeeper
    chart: cp-zookeeper-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: cp-zookeeper
      release: local-confluent-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: cp-zookeeper
        release: local-confluent-kafka
    spec:
      containers:
        - name: cp-zookeeper-server
          image: "confluentinc/cp-zookeeper:7.2.2"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          resources:
            {}
          env:
            - name : ZOOKEEPER_TICK_TIME
              value: "2000"
            - name : ZOOKEEPER_SYNC_LIMIT
              value: "5"
            - name : ZOOKEEPER_INIT_LIMIT
              value: "10"
            - name : ZOOKEEPER_MAX_CLIENT_CNXNS
              value: "60"
            - name : ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
              value: "3"
            - name : ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
              value: "24"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
