apiVersion: v1
kind: Service
metadata:
  name: local-confluent-kafka-cp-zookeeper
  labels:
    app: cp-zookeeper
    chart: cp-zookeeper-0.1.0
    release: local-confluent-kafka
    heritage: Helm
spec:
  type:
  ports:
    - port: 2181
      name: client
    - name: metrics
      port: 5556
  selector:
    app: cp-zookeeper
    release: local-confluent-kafka