apiVersion: v1
kind: Service
metadata:
  name: {{ include "cp-kafka.fullname" . }}-headless
  labels:
    app: {{ include "cp-kafka.name" . }}
  {{- include "cp-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.headless.type }}
  selector:
    app: {{ include "cp-kafka.name" . }}
  {{- include "cp-kafka.selectorLabels" . | nindent 4 }}
  ports:
    - name: tcp-kafka-int
      port: 9092
      protocol: TCP
      targetPort: tcp-kafka-int
    {{- .Values.headless.ports | toYaml | nindent 4 }}
